In [3]:
import pandas as pd
df=pd.read_csv("/content/movies_with_clusters.csv")
df

,movie_id,title,rating,genre_0,genre_1,genre_2,genre_3,genre_4,genre_5,genre_6,...,genre_10,genre_11,genre_12,genre_13,genre_14,genre_15,genre_16,genre_17,genre_18,cluster
0,1,Toy Story (1995),3.878319,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,4
1,2,GoldenEye (1995),3.206107,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
2,3,Four Rooms (1995),3.033333,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
3,4,Get Shorty (1995),3.550239,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,5,Copycat (1995),3.302326,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),1.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1678,1679,B. Monkey (1998),3.000000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,2
1679,1680,Sliding Doors (1998),2.000000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1680,1681,You So Crazy (1994),3.000000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,4
1681,1682,Scream of Stone (Schrei aus Stein) (1991),3.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
features=df.filter(like="genre_").copy()
features["rating"]=df["rating"]

In [5]:
from sklearn.preprocessing import StandardScaler
X=StandardScaler().fit_transform(features)

In [7]:
from sklearn.cluster import AgglomerativeClustering
df["cluster"]=AgglomerativeClustering(n_clusters=5).fit_predict(features)

In [19]:
def recommend(title,top_n=3):
  cluster_id=df.loc[df['title']==title,'cluster'].iloc[0]
  sim=df.query("cluster==@cluster_id and title!=@title").nlargest(top_n,'rating')
  return "\n".join(f"{r.title} (Rating: {r.rating}) - Do you want to watch also?" for _, r in sim.iterrows())

In [22]:
user_input=input("Enter the movie name:")
print(f"\n Recommendation similar to{user_input}\:n")
print(recommend(user_input))

Enter the movie name:Four Rooms (1995)

 Recommendation similar toFour Rooms (1995)\:n
Rear Window (1954) (Rating: 4.3875598086124405) - Do you want to watch also?
Usual Suspects, The (1995) (Rating: 4.385767790262173) - Do you want to watch also?
Third Man, The (1949) (Rating: 4.333333333333333) - Do you want to watch also?

In [23]:
import pandas as pd

from mlxtend.frequent_patterns import apriori, association_rules

In [24]:
data =[

    {'Milk':1,'Bread':1,'Sugar':0,'Teapowder':1},
    {'Milk':0,'Bread':1,'Sugar':1,'Teapowder':1},
    {'Milk':0,'Bread':1,'Sugar':0,'Teapowder':1},
    {'Milk':1,'Bread':1,'Sugar':0,'Teapowder':1},
    {'Milk':0,'Bread':1,'Sugar':0,'Teapowder':1}
]
df=pd.DataFrame(data)
df

   Milk  Bread  Sugar  Teapowder
0     1      1      0          1
1     0      1      1          1
2     0      1      0          1
3     1      1      0          1
4     0      1      0          1

In [25]:
frequent_itemsets=apriori(df,min_support=0.6,use_colnames=True)

/usr/local/lib/python3.11/dist-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [26]:
rules=association_rules(frequent_itemsets,metric="confidence",min_threshold=0.8)

In [27]:
print("frequently picked items ",frequent_itemsets)

frequently picked items     support            itemsets
0      1.0             (Bread)
1      1.0         (Teapowder)
2      1.0  (Bread, Teapowder)

In [28]:
import pandas as pd
import joblib
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [29]:
df=pd.read_csv("/content/movies_with_clusters.csv")
df

,movie_id,title,rating,genre_0,genre_1,genre_2,genre_3,genre_4,genre_5,genre_6,...,genre_10,genre_11,genre_12,genre_13,genre_14,genre_15,genre_16,genre_17,genre_18,cluster
0,1,Toy Story (1995),3.878319,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,4
1,2,GoldenEye (1995),3.206107,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
2,3,Four Rooms (1995),3.033333,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
3,4,Get Shorty (1995),3.550239,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,5,Copycat (1995),3.302326,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),1.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1678,1679,B. Monkey (1998),3.000000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,2
1679,1680,Sliding Doors (1998),2.000000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1680,1681,You So Crazy (1994),3.000000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,4
1681,1682,Scream of Stone (Schrei aus Stein) (1991),3.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1682 entries, 0 to 1681
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  1682 non-null   int64
 1   title     1682 non-null   object
 2   rating    1682 non-null   float64
 3   genre_0   1682 non-null   int64
 4   genre_1   1682 non-null   int64
 5   genre_2   1682 non-null   int64
 6   genre_3   1682 non-null   int64
 7   genre_4   1682 non-null   int64
 8   genre_5   1682 non-null   int64
 9   genre_6   1682 non-null   int64
 10  genre_7   1682 non-null   int64
 11  genre_8   1682 non-null   int64
 12  genre_9   1682 non-null   int64
 13  genre_10  1682 non-null   int64
 14  genre_11  1682 non-null   int64
 15  genre_12  1682 non-null   int64
 16  genre_13  1682 non-null   int64
 17  genre_14  1682 non-null   int64
 18  genre_15  1682 non-null   int64
 19  genre_16  1682 non-null   int64
 20  genre_17  1682 non-null   int64
 21  genre_18  1682 non-null   int64
 22  cluster   1682 non-null   int64
dtypes: float64(1), int64(21), object(1)
memory usage: 302.4+ KB

In [32]:
df.columns

Index(['movie_id', 'title', 'rating', 'genre_0', 'genre_1', 'genre_2',
       'genre_3', 'genre_4', 'genre_5', 'genre_6', 'genre_7', 'genre_8',
       'genre_9', 'genre_10', 'genre_11', 'genre_12', 'genre_13', 'genre_14',
       'genre_15', 'genre_16', 'genre_17', 'genre_18', 'cluster'],
      dtype='object')

In [33]:
df.shape

(1682, 23)

In [34]:
df.isnull().sum()

movie_id    0
title       0
rating      0
genre_0     0
genre_1     0
genre_2     0
genre_3     0
genre_4     0
genre_5     0
genre_6     0
genre_7     0
genre_8     0
genre_9     0
genre_10    0
genre_11    0
genre_12    0
genre_13    0
genre_14    0
genre_15    0
genre_16    0
genre_17    0
genre_18    0
cluster     0
dtype: int64